### ISSUE TITLE
Add clock frame colour as customisable.

### ISSUE THREAD

**Issue by MadhushaPrasad** [MadhushaPrasad/vue-analog-clock#1]

**Comment by martincarapia** [comment]
Customizable as in what? What part of the clock is customizable?

**Comment by MadhushaPrasad** [comment]
> Customizable as in what? What part of the clock is customizable?

![image](https://github.com/MadhushaPrasad/vue-analog-clock/assets/50085447/fd6d2d79-697c-4da9-8426-e4d2e9d34e37)
clock frame is enough for now, others will be implemented. I will create issues after fixing this.
