### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by MadhushaPrasad** [MadhushaPrasad/vue-analog-clock#2]
- [x] add links to navigate LICENSE
      ex:- [LICENSE](https://github.com/MadhushaPrasad/vue-analog-clock/blob/main/LICENSE)
- [x] Add a contribution section.
- [x] Highlight keywords
- [x] Check spelling Mistakes and fix them.
- [x] Add an NPM package link. here is the link [https://www.npmjs.com/package/vue3-analog-clock]
- [x] Add contribution section
       ex: -  
## 🌱 Contributors </br>
<a href="https://github.com/MadhushaPrasad/vue-analog-clock/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=MadhushaPrasad/vue-analog-clock" />
</a>
</br>

Please replace the above code at the bottom of the readme file.

**Comment by martincarapia** [comment]
how did you do the circle with the profile picture?
